### ISSUE TITLE
SBC ALD1D5FD - No response

### ISSUE THREAD

**Issue by git-developer** [jedie/energymeter2mqtt#6]
Hi Jens,

I saw that you started a [discussion](https://github.com/pymodbus-dev/pymodbus/discussions/1534) because of trouble connecting a SBC ALD1D5FD counter. I have the same counter (a bunch of it, to be precise) and the same problems - no response at all. Did you manage to solve your problems?

Kind regards
Christian

**Comment by git-developer** [comment]
I found the cause (USB stick with FTDI chipset) and a solution (reverse wiring and additional resistors - [details](https://github.com/pymodbus-dev/pymodbus/discussions/1534#discussioncomment-6289585)).

I'm still curious if your problem was the same.

**Comment by jedie** [comment]
No it was just a faulty usb adapter... a other ones works fine.
